aws/amazon-codeguru-profiler-python-agent

README.md, test/unit/test_profiler_runner.py
=> Fix unit test test_profiler_runner that was failing sometimes; updated README.

setup.py
*Testing:*
I run locally ``python setup.py sdist``and checked the archive does not contain the "test" folder. Prior to this change, it contained the direct files in the test folder (and no subfolders).
> pytestutils.py
help_utils.py
conftest.py
__init__.py
=> Fix setup.py to exclude the test folder.

.github/workflows/python-package.yml, .github/workflows/python-publish-live.yml, .github/workflows/python-publish-test.yml, .gitignore, DEVELOPMENT.md, README.md, codeguru_profiler_agent/agent_metadata/agent_metadata.py, setup.py
*Testing:*
* Created release [v1.0.2-dev.1](https://github.com/mirelap-amazon/amazon-codeguru-profiler-python-agent-1/releases/tag/v1.0.2-dev.1).
* Checked that the action to publish to Test PyPI was triggered and passed successfully, more details [here](https://github.com/mirelap-amazon/amazon-codeguru-profiler-python-agent-1/actions/runs/478180565).
* Checked the Test PyPI that it was released successfully: https://test.pypi.org/project/codeguru-profiler-agent/#history
* Un-marked the 1.0.2-dev.1 as "pre-release".
* This triggered the publishing to Live PyPI [here](https://github.com/mirelap-amazon/amazon-codeguru-profiler-python-agent-1/actions/runs/478185551).
* As expected, it fails with 403 because I did not setup the right API …
=> Add workflows to publish to Live and Test PyPI.

DEVELOPMENT.md
=> Update DEVELOPMENT.md with correct link for the Releases Tab.

codeguru_profiler_agent/local_aggregator.py, codeguru_profiler_agent/model/profile.py, codeguru_profiler_agent/profiler_runner.py, test/unit/model/test_profile.py
https://github.com/aws/amazon-codeguru-profiler-python-agent/issues/15
Make profile reporter to report profile before taking the sample to avoid scenario listed in issue #15 .
Also, avoid using the report time as profile end time which also a measure to avoid producing misleading data in scenario listed in issue #15 
=> Report profile before sample to avoid incorrect profile end time #15

codeguru_profiler_agent/sampling_utils.py
Creating schema in lxml can be a performance issue if we always recreate
a schema instead of reusing it.
Unfortunately this code is cython and does not appear in the flame
graph.
Tested with a local script.
This change searches for `etree.XMLSchema` in the source code
line to add a synthetic frame for it to appear in the graph.
=> Add synthetic frame for lxml schema init

codeguru_profiler_agent/model/profile.py, codeguru_profiler_agent/profiler_runner.py, test/acceptance/test_live_profiling.py, test/unit/test_profiler_runner.py
There was a bug introduced from Issue #15 where we attempt to sample
right after flushing profiles even is_profiling_in_progress has been
reset to False already
https://github.com/aws/amazon-codeguru-profiler-python-agent/issues/15
We would not attempt to sample after flushing the profile given that we have also set is_profiling_in_progress to False already.
=> [Bug fix] Do not sample right after flushing profile

CHANGELOG.rst, codeguru_profiler_agent/agent_metadata/agent_metadata.py
Update agent version on agent_metadata.py as part of the preparation to release new version onto PyPI
=> Update agent version to 1.0.4 on agent_metadata.py

codeguru_profiler_agent/local_aggregator.py, codeguru_profiler_agent/profiler_disabler.py, codeguru_profiler_agent/profiler_runner.py, test/acceptance/test_cpu_limit.py, test/unit/test_profiler_disabler.py, test/unit/test_profiler_runner.py
#19 
First iteration:
1. Introduce new concept in ProfilerDisabler. We break the should_stop_profiler function into 2 functions: should_stop_profiler and should_stop_sampling
2. should_stop_sampling is expected to be called whenever we sample. It does a check of the limit every time we sample (every second). This check ensure the cpu overhead brought by sampling and aggregating sample under the limit.
3. should_stop_profiler is expected to be called whenever we refresh config or submit profile. This check ensure the cpu overhead brought by refresh config and submit profile is under the limit. 
4. should_stop_profiler is calculated as "total cpu time spent on sampling + aggregating + refresh config + submit profile" divided by …
=> Attempt to improve implementation of ProfilerDisabler

codeguru_profiler_agent/agent_metadata/aws_ec2_instance.py, codeguru_profiler_agent/agent_metadata/fleet_info.py, test/unit/agent_metadata/test_aws_ec2_instance.py
*Testing:*
I tested one unit test on a specific host and here are the logs:
```
pytest -vv -o log_cli=true test/unit/agent_metadata/test_aws_ec2_instance.py
DEBUG    codeguru_profiler_agent.agent_metadata.fleet_info:fleet_info.py:20 Making a request to http://169.254.169.254/latest/api/token with headers set for these keys: dict_keys(['X-aws-ec2-metadata-token-ttl-seconds'])
DEBUG    codeguru_profiler_agent.agent_metadata.fleet_info:fleet_info.py:20 Making a request to http://169.254.169.254/latest/meta-data/local-hostname with headers set for these keys: dict_keys(['X-aws-ec2-metadata-token'])
DEBUG    codeguru_profiler_agent.agent_metadata.fleet_info:fleet_info.py:20 Making a request to …
```
=> Upgrade to IMDSv2 from v1 when calling EC2 Instance Metadata.

codeguru_profiler_agent/agent_metadata/aws_lambda.py, codeguru_profiler_agent/aws_lambda/lambda_handler.py, codeguru_profiler_agent/aws_lambda/profiler_decorator.py, codeguru_profiler_agent/local_aggregator.py, codeguru_profiler_agent/profiler_builder.py, codeguru_profiler_agent/sdk_reporter/sdk_reporter.py, test/acceptance/test_end_to_end_profile_and_save_to_file.py, test/acceptance/test_end_to_end_profiling.py, test/acceptance/test_live_profiling.py, test/unit/agent_metadata/test_aws_lambda.py, test/unit/aws_lambda/test_profiler_decorator.py, test/unit/file_reporter/test_file_reporter.py, test/unit/model/test_call_graph_node.py, test/unit/model/test_profile.py, test/unit/sdk_reporter/test_sdk_profile_encoder.py, test/unit/sdk_reporter/test_sdk_reporter.py, test/unit/test_codeguru_client_builder.py, test/unit/test_local_aggregator.py, test/unit/test_profiler.py, test/unit/test_profiler_disabler.py, test/unit/test_profiler_runner.py, test/unit/test_sampler.py, test/unit/test_sampling_utils.py, test/unit/utils/test_execution_state.py
As part of Lambda 1-click integration, we want the agent to create a profiling group for the user if it does not exist. To do this, we add a create_profiling_group API call in places where we could receive a ResourceNotFoundException for the PG.
*Testing:* Pytest unit tests.
Tested on a sample app in my AWS account.
=> Add create_profiling_group call in refresh_configuration and report()

codeguru_profiler_agent/profiler_disabler.py
As disabler calculate the cpu usage by usage metrics/ sampling interval and usage metrics/ profile active seconds, logging those two values help us debugging cases when disabler terminating the profiler
=> Log sampling interval and profile active second

codeguru_profiler_agent/agent_metadata/agent_metadata.py, codeguru_profiler_agent/profiler_disabler.py, codeguru_profiler_agent/sdk_reporter/profile_encoder.py, test/unit/sdk_reporter/test_sdk_profile_encoder.py
Adds serialization logic to submit `total_sample_count` as  NUM_TIMES_SAMPLED property of the AgentMetadata.
=> Adds NUM_TIMES_SAMPLED agent metadata to the submitted profile

codeguru_profiler_agent/sampling_utils.py
Whenever some python code is waiting for an item to arrive in a queue,
the current flame grpah will only show the function where the queue.get
is called, the rest of the stack is not showing. This is unfortunate
because we would need to remap those stacks into WAITING state.
This change adds another synthetic frame for this specific frame when
the source code at the end of the sampled stack has `.get(block=True`
This looks like it could trigger a lot of false positives but it will
only happen when this is the leaf of the stack so we would need this
code to call some native code that does not appear in the stack but
where we spend a lot of time.
=> Add synthetic frame for `queue.get(block=True)`

codeguru_profiler_agent/sampling_utils.py, codeguru_profiler_agent/sdk_reporter/profile_encoder.py, test/unit/sdk_reporter/test_sdk_profile_encoder.py
Running the uwsgi sample application with Python 3.8.10-3.9.2 showed incorrect module path in the UI.
This was narrowed down to `traceback` returning different results (a path with "/.").
This change makes sure the path is not leaked out.
*Testing:*
With this change, this is the logged module after removing the prefix :
- with this change: `INFO /polls/views.py`
- before this change for:
--`uwsgi`: `/Users/mirelap/Documents/workspace/JSON/aws-codeguru-profiler-python-demo-application/sample-demo-django-app//polls/viewspy`
--`runserver`: `/polls/views.py`
Before this change when running [this sample …
=> Remove current path from the module path in ProfileEncoder.

codeguru_profiler_agent/sampling_utils.py, test/help_utils.py, test/unit/test_sampling_utils.py
When using API calls from boto we often do not see the operation names
in the stack traces even though there is a dedicate function name. This
is because of the generic way that api calls are implemented in boto.
Unfortunately this is not convenient for profiling as we do not see in
flamegraphs which calls are using resources.
This change adds a specific check when we build the stacks to detect api
calls inside boto and if possible add a new frame with the operation
function name.
i.e. instead of
```
(...)
botocore.client:CloudWatch:_make_api_call
botocore.client:CloudWatch:_api_call
user_module:send_metric
```
we should end up with
```
(...)
botocore.client:CloudWatch:_make_api_call
botocore.client:CloudWatch:_api_call
botocore.client:CloudWatch:put_metric_data
user_module:send_metric …
```
=> Add operation name frame in stacks with boto api calls

codeguru_profiler_agent/sdk_reporter/profile_encoder.py, test/unit/sdk_reporter/test_sdk_profile_encoder.py
I'm reconsidering [this change](https://github.com/aws/amazon-codeguru-profiler-python-agent/pull/35) to update the module path only for this specific usecase we've found for uwsgi when the "/./" is added. If other usecases arise, we can add them later.
*Testing:*
Tested it with the task published and django app from [our sample](https://github.com/aws-samples/aws-codeguru-profiler-python-demo-application) and the Fargate app we have.
Before this change, a frame in the Fargate app looked like ` optamazonbinSampleApp:<module>`.
=> Fix bug in module path for Fargate and ignore the "/./" for Windows.

codeguru_profiler_agent/model/profile.py, test/unit/model/test_profile.py, test/unit/sdk_reporter/test_sdk_profile_encoder.py
In case of lambda where there are pause times, it should be considered when calculating active time. Essentially total pause time should be removed from [end-start]. Earlier we were considering the last sample time to be the end of the profile but in some corner cases where there is huge pause after that we would include it in the calculation even though pause is after the "end" of the profile.
So updating the way we calculate "end" of the profile. For more detailed information, please have a look at the comments.
Also, added some debug logs.
=> Fixing bug in calculating active time since start

codeguru_profiler_agent/agent_metadata/agent_metadata.py, test/acceptance/test_end_to_end_profile_and_save_to_file.py, test/unit/sdk_reporter/test_sdk_profile_encoder.py
We are currently sending the `memory_usage_mb` and `timeInMs` fields in
the agent overhead metadata, unfortunately the schema for those is INT
which means they are currently discarded when the profile is validated
at submission time. This does not prevent profiles from being accepted
but we lose the overhead data which means we will not show it in the UI.
This change converts them to int before we serialize the report.
It would be nice for the backend to accept decimals at least for the
memory since it is in MB and we may often be under 1MB. But at the
moment it is better to align to current schema.
=> Send agent overhead values as int

codeguru_profiler_agent/aws_lambda/lambda_handler.py, test/unit/aws_lambda/test_lambda_handler.py
When running on lambda functions, the CodeGuru Profiler module should be
loaded by lambda bootstrap framework instead of the customer's code.
Then we load the customer's handler function by calling the bootstarp
code directly.
We currently handle python 3.8, 3.7 and 3.6 (with some tweeks), however
for python 3.9 the lambda bootstrap module is now delegating to the
[runtime interface client](https://github.com/aws/aws-lambda-python-runtime-interface-client)
so our code must be changed to also work with this.
This changes moves the code about finding the proper function that
can load a handler function into a separate method. Unit tests are
updated to cope with this.
**Tests**
- First I ran the content of lambda_handler.py code into a lambda function and added some …
=> Update lambda handler function extraction to work with python 3.9

release_layer.py
After latest change, the layer works with python 3.9 runtime.
This change is to update the release_layer script so that the layer will officially support python 3.9 as runtime.
This will be effective only for the next version of the agent
=> Add 3.9 as supported version in the layer

CHANGELOG.rst, codeguru_profiler_agent/agent_metadata/agent_metadata.py
=> Releasing agent version 1.2.4 and layer version 11.
